server:
  port: 8090

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ecommerce"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "root"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
